### ISSUE TITLE
NoMethodError: undefined method `new_offset' for nil:NilClass

### ISSUE THREAD

**Issue by cbeer** [fcrepo4-labs/derby#8]
```
$ curl -X PUT "http://localhost:4567/basic" -H "Link: <http://www.w3.org/ns/ldp#BasicContainer>;rel=\"type\"" -d "" -H "Content-Type: text/turtle"
$ curl -v "http://localhost:4567/basic"
...
< HTTP/1.1 200 OK
$ curl -v "http://localhost:4567/basic/"
...
< HTTP/1.1 500 Internal Server Error 
NoMethodError: undefined method `new_offset' for nil:NilClass
    /Users/cabeer/.gem/ruby/2.2.3/gems/rdf-ldp-0.4.0/lib/rdf/ldp/resource.rb:305:in `etag'
    /Users/cabeer/.gem/ruby/2.2.3/gems/rdf-ldp-0.4.0/lib/rdf/ldp/resource.rb:492:in `update_headers'
    /Users/cabeer/.gem/ruby/2.2.3/gems/rdf-ldp-0.4.0/lib/rdf/ldp/resource.rb:436:in `options'
    /Users/cabeer/.gem/ruby/2.2.3/gems/rdf-ldp-0.4.0/lib/rdf/ldp/resource.rb:410:in `request'

```

**Comment by no-reply** [comment]
Thanks, I reported this to RDF::LDP, and will try to figure out why the resource doesn't get a #last_modified & how to better handle that case

**Comment by cbeer** [comment]
:+1:
